name: test

on: workflow_dispatch
jobs:
  windows-build:
    defaults:
      run:
        shell: msys2 {0}
    runs-on: windows-latest

    steps:
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
          update: true
          install: >-
            base-devel
            git
            gcc
            make
            cmake
            p7zip
    - uses: actions/checkout@v4.1.1
    - run: |
        mkdir build
        cd build
        cmake .. -DBRLCAD_COMPONENTS=libbu
        ls
